import { UnitBase } from "./unitBase";

export interface UnitCma extends UnitBase {
  item?: string; // A
  stowage_position?: string; // C
  bay?: string; // D
  row?: string; // E
  tier?: string; // F
  poo?: string; // G
  fds?: string; // J
  bl?: string; // L
  size?: string; // N
  type?: string; // O
  commodity?: string; // R
  tare_weight?: string; // S
  net_weight?: string; // T
  gross_weight?: string; // U
  vgm?: string; // V
  peso_verificado?: string; // W
  shipper?: string; // Y
  shipper_ruc?: string; // Z
  imo1?: string; // AB
  un1?: string; // AC
  imo2?: string; // AD
  un2?: string; // AE
  imo3?: string; // AF
  un3?: string; // AG
  imo4?: string; // AH
  un4?: string; // AI
  humidity?: string; // AM
  air_flow?: string; // AN
  oxigen?: string; // AO
  carbon_dioxide?: string; // AP
  olb?: string; // AQ
  olf?: string; // AR
  owl?: string; // AS
  owr?: string; // AT
  oh?: string; // AU
  condition?: string; // BA
  tecnologia?: string; // BB
  terminal?: string; // BC
  ssp_gate_out?: string; // BE
  gate_out_mty_date?: string; // BF
  gate_in_full_date?: string; // BG
  gate_out_vessel?: string; // BH
  refrendo_date?: string; // BJ
  usuario?: string; // BK
  aforo_date?: string; // BL
  ingreso_callao?: string; // BM
  dwell_time?: string; // BN
  fecha_pti?: string; // BO
  vigencia_pti?: string; // BP
  primer_pti?: string; // BQ
  segundo_pti?: string; // BR
  pti_vencido_85_d?: string; // BS
  pti_vencido_90_d?: string; // BT
  estadia_en_terminal?: string; // BU
  type_controlador?: string; // BV
  type_rcd?: string; // BW
  discharge_date?: string; // BY
  initial_motor_condition?: string; // BZ
  initial_motor_condition_date?: string; // CA
  initial_condition_box?: string; // CB
  initial_condition_box_date?: string; // CC
  motor_trademark?: string; // CD
  smart_refeer?: string; // CE
  class?: string; // CG
  depot_status?: string; // CK
  depot_zone?: string; // CL
  depot_status_pti?: string; // CM
  fecha_reparacion_pti?: string; // CN
  depot_status_box?: string; // CO
  fecha_reparacion_box?: string; // CP
  std?: string; // CQ
  fecha_std?: string; // CR
  preparado_cot?: string; // CS
  fecha_pre_cot?: string; // CT
  preparado_coa?: string; // CV
  fecha_coa?: string; // CW
  doble_tecnologia?: string; // CX

  fecha_de_lavado?: string; // CZ
  obs?: string; // DA
}
