import { BlExcel } from "interfaces/billOfLafing";
import { BookingExcel } from "interfaces/booking";
import { UnitExcel } from "interfaces/unit";
import { UnitOne } from "interfaces/unit/byLine/unitOne";
import { TemplateOption } from "types";
import { UnitCma } from "interfaces/unit/byLine/unitCma";
import { UnitMsc } from "interfaces/unit/byLine/unitMsc";
import { UnitSml } from "interfaces/unit/byLine/unitSml";

const bookingExcelExample: BookingExcel = {
  nbr: undefined,
  line: undefined,
  pol: undefined,
  pod_1: undefined,
  eq_status: undefined,
  pod_optional: undefined,
  shipper_id: undefined,
  carrier_id: undefined,
  item_qty: undefined,
  item_equipment_type: undefined,
  item_eq_grade: undefined,
  item_gross_weight: undefined,
  item_commodity_id: undefined,
  reefer_temp_reqd_c: undefined,
  reefer_humidity_pct: undefined,
  reefer_vent_required_value: undefined,
  reefer_vent_required_unit: undefined,
  reefer_co2_pct: undefined,
  reefer_o2_pct: undefined,
};

export const bookingHeaders = Object.keys(bookingExcelExample);

const blExcelExample: BlExcel = {
  carrier_visit: undefined,
  nbr: undefined,
  type: undefined,
  original_bl_nbr: undefined,
  category: undefined,
  line: undefined,
  shipper_id: undefined,
  consignee_id: undefined,

  item_nbr: undefined,
  item_is_bulk: undefined,
  item_quantity: undefined,
  item_commodity_id: undefined,
  item_weight_total_kg: undefined,
};

export const blHeaders = Object.keys(blExcelExample);

export const goodsBlHeaders = ["bl_nbr", "unit_id"];

const unitExcelExample: UnitExcel = {
  visit_vessel_id: undefined,
  routing_pod_1: undefined,
  routing_pol: undefined,
  booking_id: undefined,
  id: undefined,
  category: undefined,
  transit_state: undefined,
  freight_kind: undefined,
  line: undefined,
  grade: undefined,
  agent1: undefined,
  agent2: undefined,
  equipment_type: undefined,
  physical_build_date: undefined,
  position_slot: undefined,
  seals_seal_1: undefined,
  seals_seal_2: undefined,
  seals_seal_3: undefined,
  seals_seal_4: undefined,
  reefer_temp_reqd_c: undefined,
  reefer_temp_min_c: undefined,
  reefer_temp_max_c: undefined,
  reefer_o2_pct: undefined,
  reefer_co2_pct: undefined,
  reefer_humidity_pct: undefined,
  reefer_vent_required_value: undefined,
  reefer_is_power: undefined,
  reefer_wanted_is_power: undefined,
  unit_flex_3: undefined,
  unit_flex_5: undefined,
  unit_flex_8: undefined,
  unit_flex_9: undefined,
  unit_flex_14: undefined,
  unit_flex_15: undefined,
  ufv_flex_1: undefined,
  ufv_flex_2: undefined,
  ufv_flex_3: undefined,
  ufv_flex_4: undefined,
  ufv_flex_5: undefined,
  ufv_flex_6: undefined,
  ufv_flex_7: undefined,
  ufv_flex_8: undefined,
  ufv_flex_9: undefined,
};

export const unitHeaders = Object.keys(unitExcelExample);

const unitOneExample: UnitOne = {
  item: undefined,
  line: undefined,
  poo: undefined,
  pol: undefined,
  pod: undefined,
  fds: undefined,
  booking: undefined,
  iso: undefined,
  size: undefined,
  type: undefined,
  container: undefined,
  status: undefined,
  commodity: undefined,
  tare_weight: undefined,
  net_weight: undefined,
  gross_weight: undefined,
  vgm: undefined,
  peso_verificado: undefined,
  logistics_operator: undefined,
  shipper: undefined,
  shipper_ruc: undefined,
  customs_agency: undefined,
  temp_set: undefined,
  temp_supply: undefined,
  temp_return: undefined,
  seal1: undefined,
  seal2: undefined,
  seal3: undefined,
  seal4: undefined,
  dt: undefined,
  condition: undefined,
  tecnologia: undefined,
  terminal: undefined,
  loading_vessel: undefined,
  ssp_gate_out: undefined,
  gate_out_mty_date: undefined,
  gate_in_full_date: undefined,
  gate_out_vessel: undefined,
  dam: undefined,
  refrendo_date: undefined,
  usuario: undefined,
  aforo_date: undefined,
  ingreso_callao: undefined,
  dwell_time: undefined,
  primer_pti: undefined,
  segundo_pti: undefined,
  fecha_pti: undefined,
  vigencia_pti: undefined,
  pti_vencido_60_d: undefined,
  pti_vencido_30_d: undefined,
  estadia_en_terminal: undefined,
  type_controlador: undefined,
  type_rcd: undefined,
  discharge_vessel: undefined,
  discharge_date: undefined,
  initial_motor_condition: undefined,
  initial_motor_condition_date: undefined,
  initial_condition_box: undefined,
  initial_condition_box_date: undefined,
  motor_trademark: undefined,
  manufacture_year: undefined,
  class: undefined,
  reefer_tecnologia: undefined,
  current_pti_status: undefined,
  current_box_status: undefined,
  depot_status: undefined,
  depot_zone: undefined,
  depot_status_pti: undefined,
  fecha_reparacion_pti: undefined,
  depot_status_box: undefined,
  fecha_reparacion_box: undefined,
  std: undefined,
  preparado_cot: undefined,
  fecha_pre_cot: undefined,
  vigencia_cot: undefined,
  fecha_venc_pre_cot: undefined,
  leak_test: undefined,
  fecha_leak_test: undefined,
  preparado_coa: undefined,
  doble_tecnologia: undefined,
  cnt_lavado_pdp: undefined,
  fecha_de_lavado: undefined,
  obs: undefined,
};

export const unitOneHeader = Object.keys(unitOneExample);

const unitCmaExample: UnitCma = {
  item: undefined,
  line: undefined,
  poo: undefined,
  pol: undefined,
  pod: undefined,
  fds: undefined,
  booking: undefined,
  iso: undefined,
  size: undefined,
  type: undefined,
  container: undefined,
  status: undefined,
  commodity: undefined,
  tare_weight: undefined,
  net_weight: undefined,
  gross_weight: undefined,
  vgm: undefined,
  peso_verificado: undefined,
  logistics_operator: undefined,
  shipper: undefined,
  shipper_ruc: undefined,
  customs_agency: undefined,
  temp_set: undefined,
  temp_supply: undefined,
  temp_return: undefined,
  seal1: undefined,
  seal2: undefined,
  seal3: undefined,
  seal4: undefined,
  dt: undefined,
  condition: undefined,
  tecnologia: undefined,
  terminal: undefined,
  loading_vessel: undefined,
  ssp_gate_out: undefined,
  gate_out_mty_date: undefined,
  gate_in_full_date: undefined,
  gate_out_vessel: undefined,
  dam: undefined,
  fecha_pti: undefined,
  vigencia_pti: undefined,
  primer_pti: undefined,
  segundo_pti: undefined,
  pti_vencido_85_d: undefined,
  pti_vencido_90_d: undefined,
  type_controlador: undefined,
  type_rcd: undefined,
  discharge_vessel: undefined,
  discharge_date: undefined,
  initial_motor_condition: undefined,
  initial_motor_condition_date: undefined,
  initial_condition_box: undefined,
  initial_condition_box_date: undefined,
  motor_trademark: undefined,
  smart_refeer: undefined,
  manufacture_year: undefined,
  class: undefined,
  reefer_tecnologia: undefined,
  current_pti_status: undefined,
  current_box_status: undefined,
  depot_status: undefined,
  depot_zone: undefined,
  depot_status_pti: undefined,
  fecha_reparacion_pti: undefined,
  depot_status_box: undefined,
  fecha_reparacion_box: undefined,
  std: undefined,
  fecha_std: undefined,
  preparado_cot: undefined,
  fecha_pre_cot: undefined,
  leak_test: undefined,
  fecha_leak_test: undefined,
  preparado_coa: undefined,
  fecha_coa: undefined,
  doble_tecnologia: undefined,
  cnt_lavado_pdp: undefined,
  fecha_de_lavado: undefined,
  obs: undefined,
};

export const unitCmaHeader = Object.keys(unitCmaExample);

const unitMscExample: UnitMsc = {
  item: undefined,
  line: undefined,
  stowage_position: undefined,
  bay: undefined,
  row: undefined,
  tier: undefined,
  poo: undefined,
  pol: undefined,
  pod: undefined,
  fds: undefined,
  booking: undefined,
  bl: undefined,
  iso: undefined,
  size: undefined,
  type: undefined,
  container: undefined,
  status: undefined,
  commodity: undefined,
  tare_weight: undefined,
  net_weight: undefined,
  gross_weight: undefined,
  vgm: undefined,
  peso_verificado: undefined,
  logistics_operator: undefined,
  shipper: undefined,
  shipper_ruc: undefined,
  customs_agency: undefined,
  imo1: undefined,
  un1: undefined,
  imo2: undefined,
  un2: undefined,
  imo3: undefined,
  un3: undefined,
  imo4: undefined,
  un4: undefined,
  temp_set: undefined,
  temp_supply: undefined,
  temp_return: undefined,
  humidity: undefined,
  air_flow: undefined,
  oxigen: undefined,
  carbon_dioxide: undefined,
  olb: undefined,
  olf: undefined,
  owl: undefined,
  owr: undefined,
  oh: undefined,
  seal1: undefined,
  seal2: undefined,
  seal3: undefined,
  seal4: undefined,
  deposito_temporal: undefined,
  condition: undefined,
  tecnologia: undefined,
  terminal: undefined,
  loading_vessel: undefined,
  ssp_gate_out: undefined,
  gate_out_mty_date: undefined,
  gate_in_full_date: undefined,
  gate_out_vessel: undefined,
  dam: undefined,
  refrendo_date: undefined,
  aforo_date: undefined,
  type_controlador: undefined,
  type_rcd: undefined,
  dwell_time: undefined,
  fecha_1_pti: undefined,
  fecha_2_pti: undefined,
  fecha_3_pti: undefined,
  fecha_4_pti: undefined,
  fecha_5_pti: undefined,
  fecha_pti_actual: undefined,
  vigencia_pti: undefined,
  pti_vencido_85_d: undefined,
  pti_vencido_90_d: undefined,
  estadia_en_terminal_dias: undefined,
  discharge_vessel: undefined,
  discharge_date: undefined,
  initial_motor_condition: undefined,
  initial_motor_condition_date: undefined,
  initial_condition_box: undefined,
  initial_condition_box_date: undefined,
  manufacture_year: undefined,
  class: undefined,
  motor_trademark: undefined,
  reefer_tecnologia: undefined,
  current_pti_match: undefined,
  current_box_status: undefined,
  depot_status: undefined,
  depot_zone: undefined,
  depot_status_pti: undefined,
  fecha_reparacion_pti: undefined,
  depot_status_box: undefined,
  fecha_reparacion_box: undefined,
  leak_test: undefined,
  fecha_precoa: undefined,
  preparadas_cota: undefined,
  fecha_precot2: undefined,
  preparado_cot: undefined,
  fecha_pre_cot: undefined,
  pti_ca: undefined,
  liventus: undefined,
  fecha_liventus: undefined,
  cnt_lavados_pdp: undefined,
  fecha_de_lavado: undefined,
  doble_tecnologia: undefined,
  fecha_doble_tecnologia: undefined,
  obs_trasree: undefined,
  obs_trasree2: undefined,
  sensor_humedad: undefined,
  bateria_de_controlador: undefined,
  type_of_damage: undefined,
};
export const unitMscHeader = Object.keys(unitMscExample);

const unitSmlExample: UnitSml = {
  item: undefined,
  line: undefined,
  poo: undefined,
  pol: undefined,
  pod: undefined,
  fds: undefined,
  booking: undefined,
  iso: undefined,
  size: undefined,
  type: undefined,
  container: undefined,
  status: undefined,
  commodity: undefined,
  tare_weight: undefined,
  net_weight: undefined,
  gross_weight: undefined,
  vgm: undefined,
  peso_verificado: undefined,
  logistics_operator: undefined,
  shipper: undefined,
  shipper_ruc: undefined,
  customs_agency: undefined,
  temp_set: undefined,
  temp_supply: undefined,
  temp_return: undefined,
  seal1: undefined,
  seal2: undefined,
  seal3: undefined,
  seal4: undefined,
  dt: undefined,
  condition: undefined,
  tecnologia: undefined,
  terminal: undefined,
  loading_vessel: undefined,
  ssp_gate_out: undefined,
  gate_out_mty_date: undefined,
  gate_in_full_date: undefined,
  gate_out_vessel: undefined,
  dam: undefined,
  refrendo_date: undefined,
  usuario: undefined,
  aforo_date: undefined,
  ingreso_callao: undefined,
  dwell_time: undefined,
  primer_pti: undefined,
  segundo_pti: undefined,
  tercer_pti: undefined,
  vigencia_pti: undefined,
  pti_vencido_85_d: undefined,
  pti_vencido_90_d: undefined,
  estadia_en_terminal: undefined,
  type_controlador: undefined,
  type_rcd: undefined,
  discharge_vessel: undefined,
  discharge_date: undefined,
  initial_motor_condition: undefined,
  initial_motor_condition_date: undefined,
  initial_condition_box: undefined,
  initial_condition_box_date: undefined,
  motor_trademark: undefined,
  manufacture_year: undefined,
  class: undefined,
  reefer_tecnologia: undefined,
  current_pti_status: undefined,
  current_box_status: undefined,
  depot_status: undefined,
  depot_status_pti: undefined,
  fecha_reparacion_pti: undefined,
  depot_status_box: undefined,
  fecha_reparacion_box: undefined,
  preparado_cot: undefined,
  fecha_pre_cot: undefined,
  leak_test: undefined,
  fecha_leak_test: undefined,
  preparado_coa: undefined,
  doble_tecnologia: undefined,
  cnt_lavado_pdp: undefined,
  fecha_de_lavado: undefined,
  obs: undefined,
};
export const unitSmlHeader = Object.keys(unitSmlExample);

export const templateOptions: TemplateOption[] = [
  { value: "BK", label: "Booking" },
  { value: "BL", label: "Bill of Lading" },
  { value: "U", label: "Unit" },
];

export const headerMap: Record<string, string[]> = {
  "Stock MSC": unitMscHeader,
  "Stock ONE": unitOneHeader,
  "Stock CMA": unitCmaHeader,
  "Stock SEABOARD": unitSmlHeader,
  default: unitHeaders,
};
