import { BlExcel } from "interfaces/billOfLafing";
import { BookingExcel } from "interfaces/booking";
import { UnitExcel } from "interfaces/unit";
import { TemplateOption } from "types";

const bookingExcelExample: BookingExcel = {
  nbr: undefined,
  line: undefined,
  pol: undefined,
  pod_1: undefined,
  eq_status: undefined,
  pod_optional: undefined,
  shipper_id: undefined,
  carrier_id: undefined,
  item_qty: undefined,
  item_equipment_type: undefined,
  item_eq_grade: undefined,
  item_gross_weight: undefined,
  item_commodity_id: undefined,
  reefer_temp_reqd_c: undefined,
  reefer_humidity_pct: undefined,
  reefer_vent_required_value: undefined,
  reefer_vent_required_unit: undefined,
  reefer_co2_pct: undefined,
  reefer_o2_pct: undefined,
};

export const bookingHeaders = Object.keys(bookingExcelExample);

const blExcelExample: BlExcel = {
  nbr: undefined,
  category: undefined,
  line: undefined,
  shipper_id: undefined,
  consignee_id: undefined,
  carrier_visit: undefined,
  released_quantity: undefined,
  entered_quantity: undefined,
  bl_is_ib_to_ob_move_direct: undefined,
  item_nbr: undefined,
  item_is_bulk: undefined,
  item_piece_is_bulk: undefined,
  item_quantity: undefined,
  item_commodity_id: undefined,
  item_package_weight_kg: undefined,
  item_weight_total_kg: undefined,
  item_bl_item_is_ib_to_ob_move_direct: undefined,
  goods_unit_id: undefined,
};

export const blHeaders = Object.keys(blExcelExample);

const unitExcelExample: UnitExcel = {
  id: undefined,
  category: undefined,
  restow: undefined,
  transit_state: undefined,
  freight_kind: undefined,
  line: undefined,
  unique_key: undefined,
  grade: undefined,
  agent1: undefined,
  agent2: undefined,
  is_ib_to_ob_move_direct: undefined,
  is_verified_yard_pos: undefined,
  is_stowplan_posted: undefined,
  equipment_eqid: undefined,
  equipment_type: undefined,
  equipment_class: undefined,
  equipment_tank_rails: undefined,
  equipment_life_cycle_state: undefined,
  equipment_role: undefined,
  equipment_physical_has_wheels: undefined,
  equipment_physical_height_mm: undefined,
  equipment_physical_is_insulated: undefined,
  equipment_physical_is_permanently_out_of_service: undefined,
  equipment_physical_iso_group: undefined,
  equipment_physical_length_mm: undefined,
  equipment_physical_material: undefined,
  equipment_physical_strength_code: undefined,
  equipment_physical_tare_weight_kg: undefined,
  equipment_physical_width_mm: undefined,
  equipment_physical_grade: undefined,
  equipment_ownership_owner: undefined,
  equipment_ownership_operator: undefined,
  equipment_reefer_is_controlled_atmosphere: undefined,
  equipment_reefer_is_starvent: undefined,
  equipment_reefer_is_super_freeze: undefined,
  equipment_reefer_is_temperature_controlled: undefined,
  equipment_reefer_rfr_type: undefined,
  seals_seal_1: undefined,
  seals_seal_2: undefined,
  seals_seal_3: undefined,
  seals_seal_4: undefined,
  reefer_temp_reqd_c: undefined,
  reefer_temp_min_c: undefined,
  reefer_temp_max_c: undefined,
  reefer_temp_display_unit: undefined,
  reefer_o2_pct: undefined,
  reefer_co2_pct: undefined,
  reefer_humidity_pct: undefined,
  reefer_vent_required_value: undefined,
  reefer_vent_required_unit: undefined,
  reefer_extended_time_monitors: undefined,
  reefer_is_power: undefined,
  reefer_wanted_is_power: undefined,
  reefer_is_alarm_on: undefined,
  unit_etc_category: undefined,
  unit_etc_line: undefined,
  unit_etc_equip_condition: undefined,
  unit_flex_1: undefined,
  unit_flex_2: undefined,
  unit_flex_3: undefined,
  unit_flex_4: undefined,
  unit_flex_5: undefined,
  unit_flex_8: undefined,
  unit_flex_9: undefined,
  unit_flex_10: undefined,
  unit_flex_11: undefined,
  unit_flex_14: undefined,
  unit_flex_15: undefined,
  ufv_flex_1: undefined,
  ufv_flex_2: undefined,
  ufv_flex_3: undefined,
  ufv_flex_4: undefined,
  ufv_flex_5: undefined,
  ufv_flex_6: undefined,
  ufv_flex_7: undefined,
  ufv_flex_8: undefined,
  ufv_flex_9: undefined,
};

export const unitHeaders = Object.keys(unitExcelExample);

export const templateOptions: TemplateOption[] = [
  { value: "BK", label: "Booking" },
  { value: "BL", label: "Bill of Lading" },
  { value: "U", label: "Unit" },
];
